# Generated by Django 6.0.5 on 2026-05-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Чтобы указать цену необходимо ввести положительное число с точностью до копеек.', max_digits=8, verbose_name='Цена одежды'),
        ),
    ]
