# Generated by Django 6.0.5 on 2026-05-26 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='В поле укажите название категории, например "Обувь".', max_length=50, verbose_name='Название категории')),
                ('description', models.TextField(default='Отсутствует', help_text='Указывайте описании категории только в том случае, если категория неочивидна.', max_length=255, null=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='В поле укажите название коллекции, например "Обувь".', max_length=50, verbose_name='Название коллекции')),
                ('description', models.TextField(default='Отсутствует', help_text='Указывайте описании коллекции только в том случае, если коллекция неочивидна.', max_length=255, null=True, verbose_name='Описание коллекции')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название одежды')),
                ('description', models.TextField(max_length=512, verbose_name='Описание одежды')),
                ('price', models.DecimalField(decimal_places=2, help_text='Чтобы указать цену необходимо ввести положительное число с точностью до копеек.', max_digits=6, verbose_name='Цена одежды')),
                ('size', models.PositiveSmallIntegerField(verbose_name='Размер одежды')),
                ('photo', models.ImageField(blank=True, default='', help_text='Прикрепить фото одежды', null=True, upload_to='imgs/%Y/%m', verbose_name='Фото одежды')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания карточки одежды')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения карточки одежды')),
                ('is_exists', models.BooleanField(default=True, verbose_name='Доступен к заказу?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.category', verbose_name='Категория одежды')),
                ('collections', models.ManyToManyField(to='firstapp.collection', verbose_name='Коллекция одежды')),
            ],
            options={
                'verbose_name': 'Одежда',
                'verbose_name_plural': 'Одежды',
            },
        ),
    ]
