# Generated by Django 6.0.5 on 2026-05-29 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_clothe_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_lastname', models.CharField(max_length=100, verbose_name='Фамилия пользователя')),
                ('buyer_firstname', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('buyer_middlename', models.CharField(blank=True, default='Отсутствует', max_length=100, null=True, verbose_name='Отчетство пользователя')),
                ('comment', models.TextField(blank=True, default='Отсутствует', max_length=256, null=True, verbose_name='Комментарий к заказу')),
                ('delivery_address', models.CharField(blank=True, default='Самовывоз', max_length=512, null=True, verbose_name='Адрес доставки')),
                ('delivery_type', models.CharField(choices=[('SH', 'Самовывоз'), ('CR', 'Курьер'), ('PP', 'Пункт выдачи заказов')], default='SH', max_length=2, verbose_name='Тип доставки')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('datetime_finish', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Pos_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество одежды')),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='Скидка')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.clothe', verbose_name='Одежда')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция в заказе',
                'verbose_name_plural': 'Позиции в заказе',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='clothes',
            field=models.ManyToManyField(through='firstapp.Pos_Order', to='firstapp.clothe', verbose_name='Позиции заказа'),
        ),
    ]
